### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by brick713** [fy0/Icarus#5]
psycopg2.ProgrammingError: 错误:  类型 "citext" 不存在  运行后爆这个错误，怎么解决？

**Comment by brick713** [comment]
自己解决了～

**Comment by fy0** [comment]
呃 怎么触发的，又是怎么解决的呢？

**Comment by brick713** [comment]
配置 psql 的时候必须加这么一段
sql =# \c icarus
CREATE EXTENSION citext;

另外能给个联系方式么，部署完成了访问是404 不知道为什么

**Comment by brick713** [comment]
另外你的private.js的配置按照示例也会有 error 我这样改了之后就没问题了：
// 单端口方案
var host = window.location.host

export default {
    remote: {
        API_SERVER: '//' + host,
        WS_SERVER: 'ws://' + host + '/ws'
    },
    qiniu: {
        server: 'http://upload.qiniu.com',
        // host: '//test-bucket.myrpg.cn',
        suffix: 'normal'
    }
}

**Comment by fy0** [comment]
@brick713 发你邮箱了。回头我把readme更新一下。

哦 这个应该是分号问题，vue cli 2项目不检测这些杂色配置文件里的分号，但是新的cli 3项目会

**Comment by brick713** [comment]
加你了~
