### ISSUE TITLE
希望支持mysql数据库

### ISSUE THREAD

**Issue by newte88** [fy0/Icarus#7]

**Comment by fy0** [comment]
这个后面再说吧……我要先把基础的功能完善起来。

一方面我离开MySQL太久了，另一方面在比较有限的业余时间中，在持续实现功能的同时，我没有更多精力去做双份的数据库支持、版本测试、以及升级脚本测试了……

**Comment by gzxultra** [comment]
你不是用的 ORM 么？应该能做到 DB 无关啊

**Comment by fy0** [comment]
使用了数据库的部分扩展，而且不可避免的还有一些sql语句，ORM直接切换太乐观了。
